export const enum ExceptionCodeName {
  INVALID_ENVIRONMENT_VARIABLE = 'INVALID_ENVIRONMENT_VARIABLE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_MEDIA_FORMAT = 'INVALID_MEDIA_FORMAT',
  QUERY_FAILED_ERROR = 'QUERY_FAILED_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_JWT = 'INVALID_JWT',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  USER_EMAIL_CONFLICT = 'USER_EMAIL_CONFLICT',
  PHYSICAL_ACTIVITY_LEVEL_NOT_FOUND = 'PHYSICAL_ACTIVITY_LEVEL_NOT_FOUND',
  FOOD_LIFESTYLE_NOT_FOUND = 'FOOD_LIFESTYLE_NOT_FOUND',
  INVALID_POST_ID = 'INVALID_POST_ID',
  POST_DOES_NOT_EXIST_OR_YOU_DO_NOT_OWN_THIS_POST = 'POST_DOES_NOT_EXIST_OR_YOU_DO_NOT_OWN_THIS_POST',
<<<<<<< HEAD
  POST_DOES_NOT_EXIST = 'POST_DOES_NOT_EXIST',
  COMMENT_DOES_NOT_EXIST_OR_YOU_DO_NOT_OWN_THIS_COMMENT = 'COMMENT_DOES_NOT_EXIST_OR_YOU_DO_NOT_OWN_THIS_COMMENT',
=======
  COMMENT_DOES_NOT_EXIST_OR_YOU_DO_NOT_OWN_THIS_COMMENT = 'COMMENT_DOES_NOT_EXIST_OR_YOU_DO_NOT_OWN_THIS_COMMENT',
  POST_DOES_NOT_EXIST = 'POST_DOES_NOT_EXIST',
>>>>>>> Created post and comment relation, updated comment post request, so you can post comment to a post. Implemented endpoint where you can get all comments from specific post
}
