export const enum ExceptionCodeName {
  INVALID_ENVIRONMENT_VARIABLE = 'INVALID_ENVIRONMENT_VARIABLE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_MEDIA_FORMAT = 'INVALID_MEDIA_FORMAT',
  QUERY_FAILED_ERROR = 'QUERY_FAILED_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_JWT = 'INVALID_JWT',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  USER_EMAIL_CONFLICT = 'USER_EMAIL_CONFLICT',
  PHYSICAL_ACTIVITY_LEVEL_NOT_FOUND = 'PHYSICAL_ACTIVITY_LEVEL_NOT_FOUND',
  FOOD_LIFESTYLE_NOT_FOUND = 'FOOD_LIFESTYLE_NOT_FOUND',
}
